load("@bazel_skylib//rules:build_test.bzl", "build_test")

build_test(
    name = "build_test",
    targets = [
        "//src/main/java/io/servicetalk/examples/grpc/helloworld/blocking:blocking_server",
        "//src/main/java/io/servicetalk/examples/grpc/helloworld/blocking:blocking_client",
    ],
)
