# Copyright © 2026 Apple Inc. and the ServiceTalk project authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(name = "rules_servicetalk_tests_servicetalk")

bazel_dep(name = "rules_servicetalk", version = "0.0.0")
local_path_override(
    module_name = "rules_servicetalk",
    path = "../../",
)

bazel_dep(name = "bazel_skylib", version = "1.8.1")
bazel_dep(name = "rules_java", version = "8.15.2")
bazel_dep(name = "rules_jvm_external", version = "6.10")

#### Servicetalk ####

register_toolchains("@rules_servicetalk//servicetalk:st-toolchain")

#### Maven servicetalk dependencies ####
io_service_talk_version = "0.42.65"

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "maven",
    artifacts = [
        "io.servicetalk:servicetalk-grpc-netty:" + io_service_talk_version,
    ],
    fail_if_repin_required = True,
    fetch_sources = True,
    known_contributing_modules = [
        "protobuf",
        "rules_servicetalk_tests_servicetalk",
    ],
    lock_file = ":maven_install.json",
    strict_visibility = True,
)
use_repo(
    maven,
    "maven",
)
